import env from './environments'

const themeConstant: ThemeConstant = env.themeName !== 'acleda' ? {
    MAIN_COLOR: '255,255,255',
    MENU_SELECTED_COLOR: '#5385C8',
    DRAWER_LIGHT_BG_COLOR: '#1A3351',
    DRAWER_DARK_BG_COLOR: '#1A3351',
    DRAWER_LIGHT_TEXT_COLOR: '#FFF',
    DRAWER_DARK_TEXT_COLOR: '#FFF',
    HEADER_LIGHT_BG_COLOR: '#5385C8',
    HEADER_DARK_BG_COLOR: '#1A3351',
    MENU_TEXT_COLOR: '#fff',
    PRIMARY_LIGHT: '#8ab6dc',
    PRIMARY_DARK: '#1A3351',
    PRIMARY_MAIN: '#5385C8',
    PRIMARY_CONTRAST_TEXT: '#fff',
    SECONDARY_LIGHT: '#f1d078',
    SECONDARY_DARK: '#5a4819',
    SECONDARY_MAIN: '#CBA02D',
    SECONDARY_CONTRAST_TEXT: '#fff',
    GOLDEN_LIGHT: '#f1d078',
    GOLDEN_DARK: '#5a4819',
    GOLDEN_MAIN: '#CBA02D',
    GOLDEN_CONTRAST_TEXT: '#fff',
    ERROR_LIGHT: '#FF5B3F',
    ERROR_DARK: '#E8381A',
    ERROR_MAIN: '#FF3E1D',
    ERROR_CONTRAST_TEXT: '#fff',
    WARNING_LIGHT: '#FFB826',
    WARNING_DARK: '#E89C00',
    WARNING_MAIN: '#FFAB00',
    WARNING_CONTRAST_TEXT: '#fff',
    INFO_LIGHT: '#29CCEF',
    INFO_DARK: '#03B1D7',
    INFO_MAIN: '#03C3EC',
    INFO_CONTRAST_TEXT: '#fff',
    SUCCESS_LIGHT: '#86E255',
    SUCCESS_DARK: '#67C932',
    SUCCESS_MAIN: '#71DD37',
    SUCCESS_CONTRAST_TEXT: '#fff',
    GREY_50: '#FAFAFA',
    GREY_100: '#F5F5F5',
    GREY_200: '#EEEEEE',
    GREY_300: '#E0E0E0',
    GREY_400: '#BDBDBD',
    GREY_500: '#9E9E9E',
    GREY_600: '#757575',
    GREY_700: '#616161',
    GREY_800: '#424242',
    GREY_900: '#212121',
    GREY_A100: '#F5F5F5',
    GREY_A200: '#EEEEEE',
    GREY_A400: '#BDBDBD',
    GREY_A700: '#616161',
    WHITE: '#fff',
    BLACK: '#000',
    TRANSPARENT: 'transparent',
    DEFAULT: '#696CFF',
    DEFAULT_LIGHT: '#8082FF',
    DEFAULT_DARK: '#6062E8',
    DEFAULT_CONTRAST_TEXT: '#fff',
    DEFAULT_MAIN: '#696CFF',
    DEFAULT_MAIN_LIGHT: '#8082FF',
    DEFAULT_MAIN_DARK: '#6062E8',
    DEFAULT_MAIN_CONTRAST_TEXT: '#fff',
    DEFAULT_DARK_LIGHT: '#8082FF',
    DEFAULT_DARK_DARK: '#6062E8',
    DEFAULT_DARK_CONTRAST_TEXT: '#fff',
} : {
    MAIN_COLOR: '50, 71, 92',
    MENU_SELECTED_COLOR: '#696CFF',
    DRAWER_LIGHT_BG_COLOR: '#f5f5f5',
    HEADER_LIGHT_BG_COLOR: '#f5f5f5',
    HEADER_DARK_BG_COLOR: '#232333',
    DRAWER_LIGHT_TEXT_COLOR: '#FFF',
    DRAWER_DARK_TEXT_COLOR: '#FFF',
    PRIMARY_LIGHT: '#8082FF',
    PRIMARY_DARK: '#6062E8',
    PRIMARY_MAIN: '#696CFF',
    MENU_TEXT_COLOR: '#000',
    PRIMARY_CONTRAST_TEXT: '#fff',
    SECONDARY_LIGHT: '#F3BE33',
    SECONDARY_DARK: '#B38C24',
    SECONDARY_MAIN: '#CBA02D',
    SECONDARY_CONTRAST_TEXT: '#fff',
    GOLDEN_LIGHT: '#F3BE33',
    GOLDEN_DARK: '#B38C24',
    GOLDEN_MAIN: '#CBA02D',
    GOLDEN_CONTRAST_TEXT: '#fff',
    ERROR_LIGHT: '#FF5B3F',
    ERROR_DARK: '#E8381A',
    ERROR_MAIN: '#FF3E1D',
    ERROR_CONTRAST_TEXT: '#fff',
    WARNING_LIGHT: '#FFB826',
    WARNING_DARK: '#E89C00',
    WARNING_MAIN: '#FFAB00',
    WARNING_CONTRAST_TEXT: '#fff',
    INFO_LIGHT: '#29CCEF',
    INFO_DARK: '#03B1D7',
    INFO_MAIN: '#03C3EC',
    INFO_CONTRAST_TEXT: '#fff',
    SUCCESS_LIGHT: '#86E255',
    SUCCESS_DARK: '#67C932',
    SUCCESS_MAIN: '#71DD37',
    SUCCESS_CONTRAST_TEXT: '#fff',
    GREY_50: '#FAFAFA',
    GREY_100: '#F5F5F5',
    GREY_200: '#EEEEEE',
    GREY_300: '#E0E0E0',
    GREY_400: '#BDBDBD',
    GREY_500: '#9E9E9E',
    GREY_600: '#757575',
    GREY_700: '#616161',
    GREY_800: '#424242',
    GREY_900: '#212121',
    GREY_A100: '#F5F5F5',
    GREY_A200: '#EEEEEE',
    GREY_A400: '#BDBDBD',
    GREY_A700: '#616161',
    WHITE: '#fff',
    BLACK: '#000',
    TRANSPARENT: 'transparent',
    DEFAULT: '#696CFF',
    DEFAULT_LIGHT: '#8082FF',
    DEFAULT_DARK: '#6062E8',
    DEFAULT_CONTRAST_TEXT: '#fff',
    DEFAULT_MAIN: '#696CFF',
    DEFAULT_MAIN_LIGHT: '#8082FF',
    DEFAULT_MAIN_DARK: '#6062E8',
    DEFAULT_MAIN_CONTRAST_TEXT: '#fff',
    DEFAULT_DARK_LIGHT: '#8082FF',
    DEFAULT_DARK_DARK: '#6062E8',
    DEFAULT_DARK_CONTRAST_TEXT: '#fff',
    
}
type ThemeConstant = {
    MAIN_COLOR?: string;
    MENU_SELECTED_COLOR?: string;
    DRAWER_LIGHT_BG_COLOR?: string;
    DRAWER_LIGHT_TEXT_COLOR?: string;
    DRAWER_DARK_TEXT_COLOR?: string;
    HEADER_LIGHT_BG_COLOR?: string;
    DRAWER_DARK_BG_COLOR?: string;
    HEADER_DARK_BG_COLOR?: string;
    PRIMARY_LIGHT: string;
    PRIMARY_DARK: string;
    MENU_TEXT_COLOR?: string;
    PRIMARY_MAIN: string;
    PRIMARY_CONTRAST_TEXT: string;
    SECONDARY_LIGHT: string;
    SECONDARY_DARK: string;
    SECONDARY_MAIN: string;
    SECONDARY_CONTRAST_TEXT: string;
    GOLDEN_LIGHT: string;
    GOLDEN_DARK: string;
    GOLDEN_MAIN: string;
    GOLDEN_CONTRAST_TEXT: string;
    ERROR_LIGHT: string;
    ERROR_DARK: string;
    ERROR_MAIN: string;
    ERROR_CONTRAST_TEXT: string;
    WARNING_LIGHT: string;
    WARNING_DARK: string;
    WARNING_MAIN: string;
    WARNING_CONTRAST_TEXT: string;
    INFO_LIGHT: string;
    INFO_DARK: string;
    INFO_MAIN: string;
    INFO_CONTRAST_TEXT: string;
    SUCCESS_LIGHT: string;
    SUCCESS_DARK: string;
    SUCCESS_MAIN: string;
    SUCCESS_CONTRAST_TEXT: string;
    GREY_50: string;
    GREY_100: string;
    GREY_200: string;
    GREY_300: string;
    GREY_400: string;
    GREY_500: string;
    GREY_600: string;
    GREY_700: string;
    GREY_800: string;
    GREY_900: string;
    GREY_A100: string;
    GREY_A200: string;
    GREY_A400: string;
    GREY_A700: string;
    WHITE: string;
    BLACK: string;
    TRANSPARENT: string;
    DEFAULT: string,
    DEFAULT_LIGHT:string,
    DEFAULT_DARK:string,
    DEFAULT_CONTRAST_TEXT:string,
    DEFAULT_MAIN:string,
    DEFAULT_MAIN_LIGHT:string,
    DEFAULT_MAIN_DARK:string,
    DEFAULT_MAIN_CONTRAST_TEXT:string,
    DEFAULT_DARK_LIGHT:string,
    DEFAULT_DARK_DARK:string,
    DEFAULT_DARK_CONTRAST_TEXT:string
}
export default themeConstant;